# netlify.toml

[build]
  functions = "netlify/functions"
  publish   = "."

[functions]
  # bundling config
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

# Timeout NUR für diese eine Function angeben
[functions."generate-pdf"]
  timeout = 30

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"


# (Optional) SPA-Redirect, falls du eine Single-Page-App hast
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
